export class UserRegistrationInfo {
  id: number;
  registrationNo: string;
  instituteId: string;
  registrationComplete: boolean;
  user: {
    id: number,
    contactNo: string,
    name: string,
    userName: string,
    email: string,
    positionId: string,
    userUniqueid: string,
    imageUrl: string,
    userTypeId: string
  };
  studentInfo: {
    id: number;
    bankBranch: string;
    bankName: string;
    branchRoutingNo: string;
    gender: string;
    mobileBankingAccNo: string;
    mobileBankingAccProvider: string;
    studentAccountName: string;
    studentAccountNo: string;
    studentAddress: string;
    studentBirthDate: string;
    studentBirthRegNo: string;
    studentFatherName: string;
    studentMaritalStatus: string;
    studentMobileNo: string;
    studentMotherName: string;
    studentNID: string;
    studentName: string;
    studentStatus: string;
    upazilaId: string;
    districtId: string;
    divisionId: string;
    postCode: string;
    studentPriorityCategoryId: string;
    studentInfoComplete: boolean;
  };
  studentDegreeEducation: {
    id: number,
    instituteId: number,
    studentAcademicYear: string,
    studentAdmissionYear: string,
    studentClassId: string,
    studentCourse: string,
    studentSession: string,
    studentDegreeEducationComplete: boolean;
    institute: {
      id: number;
      instituteContactNumber: string;
      instituteEIINNo: string;
      instituteName: string;
      instituteType: string;
      upazilaId: number;
      districtId: number;
    };
  };
  studentHscEducation: {
    id: number,
    instituteName: string,
    passingYear: string,
    rollNumber: string,
    educationGroup: string,
    board: string,
    registrationNumber: string,
    session: string,
    gpa: string,
    hscEducationInfoComplete: boolean;
  };

  studentGuardian: {
    id: number,
    guardianName: string,
    guardianOccupation: string,
    guardianAddress: string,
    postCode: string,
    upazilaId: string,
    districtId: string,
    guardianMobileNo: string,
    noOfFamilyMember: string,
    noOfEarningMember: string,
    studentRelationId: string,
    agriculturalLand: string,
    nonAgriculturalLand: string,
    totalLand: string,
    annualIncome: string,
    incomeInWords: string,
    relationName: string,
    otherGuardianNid: string,
    landLocationId: string,
    studentGuardianInfoComplete: boolean,
  };
  studentDegreeEducationId: number;
  studentGuardianId: number;
  studentInfoId: number;
  studentHscEducationId: number;
}
